### ISSUE TITLE
Verification page: Duplicate CSS rules

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-client-template#13]
Check: https://github.com/boolean-uk/team-dev-client-template/blob/main/src/pages/verification/verification.css

**Comment by chris2733** [comment]
This is all good - its setting margin right/bottom using max and min width respectively

**Comment by dearshrewdwit** [comment]
Ah - my old eyes! Thanks 👍

**Comment by dearshrewdwit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Example task]](https://trello.com/c/q1VZnGEA/12-example-task)
